# Generated by Django 5.1.8 on 2025-05-05 09:24

import django.core.validators
import evaluations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(blank=True, db_index=True, null=True, verbose_name='Correcte')),
                ('answered_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Répondu le')),
                ('delta_time', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(200)], verbose_name='Durée')),
                ('status', models.CharField(choices=[('pending', 'En attente de correction'), ('discarded', 'Abandonnée'), ('timeout', 'Timeout'), ('partial', 'Correct partiellement'), ('correct', 'Correcte'), ('incorrect', 'Incorrecte')], db_index=True, default='pending', max_length=20, verbose_name='Statut')),
                ('score', models.IntegerField(default=0, verbose_name='Résultat')),
            ],
            options={
                'verbose_name': 'Réponse',
                'verbose_name_plural': 'Réponses',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to=evaluations.models._upload_to, verbose_name='Image')),
                ('difficulty', models.CharField(choices=[('beginner', "Débutant 0- 2 ans d'expérience"), ('intermediate', "Intermédiaire 3-5 ans d'expérience"), ('expert', "Expert 5+ ans d'expérience")], db_index=True, default='beginner', max_length=20, verbose_name='Difficulty')),
            ],
            options={
                'verbose_name': 'Evaluation',
                'verbose_name_plural': 'Evaluations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Résultat')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Soumis le')),
            ],
            options={
                'verbose_name': 'Soumission',
                'verbose_name_plural': 'Soumissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Commencé le')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé le')),
            ],
            options={
                'verbose_name': 'Tentative de soumission',
                'verbose_name_plural': 'Tentatives de soumission',
            },
        ),
    ]
