# Generated by Django 5.1.8 on 2025-05-05 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('evaluations', '0001_initial'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.question', verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='selected_choices',
            field=models.ManyToManyField(blank=True, related_name='answers', to='questions.choice', verbose_name='Choix sélectionnés'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='core.profession', verbose_name='Profession'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to=settings.AUTH_USER_MODEL, verbose_name='Créateur'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='technology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='core.technology', verbose_name='Technologie'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['score'], name='evaluations_score_b19aab_idx'),
        ),
        migrations.AddField(
            model_name='submissionattempt',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='submissionattempt',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='evaluations.evaluation', verbose_name='Évaluation'),
        ),
        migrations.AddField(
            model_name='submissionattempt',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='attempts', to='questions.question', verbose_name='Questions'),
        ),
        migrations.AddField(
            model_name='submissionattempt',
            name='submission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempt', to='evaluations.submission', verbose_name='Soumission'),
        ),
        migrations.AddField(
            model_name='answer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='evaluations.submissionattempt', verbose_name='Tentative de soumission'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['slug'], name='evaluations_slug_f3a994_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['difficulty'], name='evaluations_difficu_05aff5_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionattempt',
            index=models.Index(fields=['started_at'], name='evaluations_started_7b3ff1_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['status'], name='evaluations_status_620da5_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['is_correct'], name='evaluations_is_corr_60035d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('attempt', 'question')},
        ),
    ]
