# Generated by Django 5.2.5 on 2025-08-28 14:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='candidateprofile',
            index=models.Index(fields=['open_to_work'], name='candidates__open_to_89ce69_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateprofile',
            index=models.Index(fields=['years_experience'], name='candidates__years_e_9042ed_idx'),
        ),
    ]
