# Generated by Django 5.2.5 on 2026-09-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='resume',
            field=models.FileField(blank=True, help_text='PDF uniquement', null=True, upload_to='resumes/private/', verbose_name='CV'),
        ),
    ]
