# Generated by Cascade to ensure missing column 'open_to_work' exists on candidates_candidateprofile
from django.db import migrations


def ensure_open_to_work(apps, schema_editor):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        # Inspect table columns
        cursor.execute("PRAGMA table_info('candidates_candidateprofile')")
        cols = [row[1] for row in cursor.fetchall()]
        if 'open_to_work' not in cols:
            # Add the missing column with a default value 0 (False)
            schema_editor.execute("ALTER TABLE candidates_candidateprofile ADD COLUMN open_to_work BOOLEAN NOT NULL DEFAULT 0")


def noop(apps, schema_editor):
    # No-op reverse
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0002_candidateprofile_candidates__open_to_89ce69_idx_and_more"),
    ]

    operations = [
        migrations.RunPython(ensure_open_to_work, reverse_code=noop),
    ]
