# Generated by Django 5.2.5 on 2026-07-21 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Domaine',
                'verbose_name_plural': 'Domaines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='questions.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Critère',
                'verbose_name_plural': 'Critères',
                'ordering': ['name'],
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.AddField(
            model_name='category',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='questions.domain', verbose_name='Domaine'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('level', models.IntegerField(blank=True, choices=[(1, 'Débutant'), (2, 'Intermédiaire'), (3, 'Expert')], default=1, verbose_name='Niveau')),
                ('question_type', models.CharField(choices=[('MCQ', 'Choix multiple'), ('UCQ', 'Choix unique'), ('OA', 'Réponse ouverte')], default='OA', max_length=3, verbose_name='Type de question')),
                ('question_category', models.CharField(choices=[('NORMAL', 'Normal'), ('PERSONALITY', 'Test de personnalité'), ('LOGICAL', 'Test logique')], default='NORMAL', max_length=20, verbose_name='Catégorie de question')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questions.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Texte')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Correcte')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='questions.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Choix',
                'verbose_name_plural': 'Choix',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='questions.criteria', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='questions', to='questions.tag', verbose_name='Tags'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'domain')},
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('name', 'criteria'), name='unique_tag_per_criteria'),
        ),
    ]
