# Generated by Django 5.1.8 on 2025-05-05 09:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('evaluations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('text', models.TextField(verbose_name='Titre')),
                ('explanation', models.TextField(help_text='Explication de la réponse', verbose_name='Explication')),
                ('difficulty', models.CharField(choices=[('easy', 'Facile'), ('medium', 'Moyen'), ('hard', 'Difficile')], db_index=True, max_length=10, verbose_name='Difficulté')),
                ('status', models.CharField(choices=[('pending', 'En attente de validation'), ('published', 'Publiée'), ('rejected', 'Rejetée')], db_index=True, default='pending', max_length=10, verbose_name='Statut')),
                ('duration', models.IntegerField(default=20, help_text='Durée en secondes', validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(200)], verbose_name='Durée')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='evaluations.evaluation', verbose_name='Évaluation')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='Éditeur')),
                ('technology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.technology', verbose_name='Technologie')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('text', models.TextField(verbose_name='Texte')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Est correct')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='questions.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Choix',
                'verbose_name_plural': 'Choix',
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['status'], name='questions_q_status_fca2ef_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['difficulty'], name='questions_q_difficu_5db314_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['evaluation'], name='questions_q_evaluat_5717cf_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['technology'], name='questions_q_technol_dbdb26_idx'),
        ),
        migrations.AddIndex(
            model_name='choice',
            index=models.Index(fields=['question', 'is_correct'], name='questions_c_questio_232821_idx'),
        ),
    ]
