# Generated by Django 5.2.5 on 2026-08-26 14:23

from django.db import migrations


PROFILES = [
    {
        'domain': 'Enseignant',
        'categories': ['Lycée', 'Collège', 'Section anglophone', 'Section francophone'],
    },
    {'domain': 'Directeur des opérations', 'categories': ['Général']},
    {'domain': 'Architecte', 'categories': ['Général']},
    {'domain': 'Chauffeur de camions', 'categories': ['Général']},
    {'domain': 'Agent de sécurité', 'categories': ['Général']},
    {'domain': 'Topographe', 'categories': ['Général']},
]


def create_default_profiles(apps, schema_editor):
    Domain = apps.get_model('questions', 'Domain')
    Category = apps.get_model('questions', 'Category')
    Criteria = apps.get_model('questions', 'Criteria')
    Tag = apps.get_model('questions', 'Tag')

    for item in PROFILES:
        domain, _ = Domain.objects.get_or_create(name=item['domain'])
        for category_name in item['categories']:
            category, _ = Category.objects.get_or_create(
                name=category_name,
                domain=domain,
            )
            criteria, _ = Criteria.objects.get_or_create(
                name='Général',
                category=category,
            )
            Tag.objects.get_or_create(
                name='Général',
                criteria=criteria,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_profiles, migrations.RunPython.noop),
    ]
