# Generated by Django 5.2.5 on 2026-08-26 14:34

from django.db import migrations


PROFILES = [
    {'domain': 'Comptable', 'categories': ['Général']},
    {'domain': 'Secrétaire de direction', 'categories': ['Général']},
    {'domain': 'Assistant administratif', 'categories': ['Général']},
    {'domain': 'Ressources humaines', 'categories': ['Général']},
    {'domain': 'Juriste', 'categories': ['Général']},
    {'domain': 'Avocat', 'categories': ['Général']},
    {'domain': 'Notaire', 'categories': ['Général']},
    {'domain': 'Consultant', 'categories': ['Général']},
    {'domain': 'Agent commercial', 'categories': ['Général']},
    {'domain': 'Chargé de clientèle', 'categories': ['Général']},
    {'domain': 'Marketing et communication', 'categories': ['Général']},
    {'domain': 'Community manager', 'categories': ['Général']},
    {'domain': 'Data analyst', 'categories': ['Général']},
    {'domain': 'Développeur informatique', 'categories': ['Général']},
    {'domain': 'Technicien réseau', 'categories': ['Général']},
    {'domain': 'Infirmier', 'categories': ['Général']},
    {'domain': 'Médecin généraliste', 'categories': ['Général']},
    {'domain': 'Pharmacien', 'categories': ['Général']},
    {'domain': 'Sage-femme', 'categories': ['Général']},
    {'domain': 'Mécanicien', 'categories': ['Général']},
    {'domain': 'Électricien', 'categories': ['Général']},
    {'domain': 'Plombier', 'categories': ['Général']},
    {'domain': 'Menuisier', 'categories': ['Général']},
    {'domain': 'Soudeur', 'categories': ['Général']},
    {'domain': 'Cuisinier', 'categories': ['Général']},
    {'domain': 'Boulanger et pâtissier', 'categories': ['Général']},
    {'domain': 'Coiffeur et esthéticien', 'categories': ['Général']},
    {'domain': 'Agent de nettoyage', 'categories': ['Général']},
    {'domain': 'Jardinier et paysagiste', 'categories': ['Général']},
    {'domain': 'Magasinier', 'categories': ['Général']},
    {'domain': 'Logisticien', 'categories': ['Général']},
    {'domain': 'Banquier et conseiller financier', 'categories': ['Général']},
    {'domain': 'Agent immobilier', 'categories': ['Général']},
    {'domain': 'Pompiste', 'categories': ['Général']},
    {'domain': 'Conducteur de bus', 'categories': ['Général']},
    {'domain': 'Pédagogue et éducateur', 'categories': ['Général']},
    {'domain': 'Psychologue', 'categories': ['Général']},
    {'domain': 'Assistant social', 'categories': ['Général']},
    {'domain': 'Téléconseiller', 'categories': ['Général']},
    {'domain': 'Traducteur et interprète', 'categories': ['Général']},
    {'domain': 'Journaliste', 'categories': ['Général']},
]


def create_more_profiles(apps, schema_editor):
    Domain = apps.get_model('questions', 'Domain')
    Category = apps.get_model('questions', 'Category')
    Criteria = apps.get_model('questions', 'Criteria')
    Tag = apps.get_model('questions', 'Tag')

    for item in PROFILES:
        domain, _ = Domain.objects.get_or_create(name=item['domain'])
        for category_name in item['categories']:
            category, _ = Category.objects.get_or_create(
                name=category_name,
                domain=domain,
            )
            criteria, _ = Criteria.objects.get_or_create(
                name='Général',
                category=category,
            )
            Tag.objects.get_or_create(
                name='Général',
                criteria=criteria,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_add_default_profiles'),
    ]

    operations = [
        migrations.RunPython(create_more_profiles, migrations.RunPython.noop),
    ]
