# Generated by Django 5.1.8 on 2025-08-01 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='job_type',
            field=models.CharField(
                choices=[('full_time', 'Temps plein'), ('part_time', 'Temps partiel'), ('cdi', 'CDI'), ('cdd', 'CDD'),
                         ('internship', 'Stage'), ('remote', 'Télétravail'), ('freelance', 'Freelance')], max_length=20,
                verbose_name='Type de contrat'),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('applicant_name', models.CharField(max_length=255, verbose_name='Nom du candidat')),
                ('applicant_email', models.EmailField(max_length=254, verbose_name='Email du candidat')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='CV')),
                ('cover_letter', models.TextField(blank=True, verbose_name='Lettre de motivation')),
                ('ai_analysis', models.TextField(blank=True, verbose_name='Analyse IA du CV')),
                ('ai_decision', models.BooleanField(blank=True, null=True, verbose_name='Décision IA')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('job_offer',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications',
                                   to='jobs.joboffer', verbose_name="Offre d'emploi")),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
