# Generated by Cascade to fix missing timestamp columns on accounts_user
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(verbose_name="Date de création", default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(verbose_name="Date de modification", default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
