version: '3.8'

services:
  web:
    build: .
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - ./.env
    expose:
      - 8000
    networks:
      - wib-network

  nginx:
    image: nginx:1.23-alpine
    restart: always
    ports:
      - "${NGINX_PORT:-80}:80"
    volumes:
      - static_volume:/usr/share/nginx/html/static
      - media_volume:/usr/share/nginx/html/media
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web
    networks:
      - wib-network

networks:
  wib-network:
    driver: bridge

volumes:
  static_volume:
  media_volume:
