version: '3.8'

services:
  web:
    build: .
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health/" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - logs_volume:/app/logs
    expose:
      - 8000
    networks:
      - wib-network

  nginx:
    image: nginx:alpine
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    expose:
      - 80
    volumes:
      - static_volume:/usr/share/nginx/html/static
      - media_volume:/usr/share/nginx/html/media
      - ./nginx:/etc/nginx/conf.d
      - nginx_logs:/var/log/nginx
      - logs_volume:/var/log/nginx
    depends_on:
      - web
    networks:
      - wib-network

networks:
  wib-network:
    driver: bridge

volumes:
  static_volume:
  media_volume:
  logs_volume:
  nginx_logs:
