version: '3.8'

services:
  web:
    build: .
    container_name: wib_challenge_web
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./static:/app/static
      - ./media:/app/media
      - ./db.sqlite3:/app/db.sqlite3
    restart: unless-stopped
