# Generated by Django 5.1.8 on 2025-08-18 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la catégorie')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug URL')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': "Catégorie d'emploi",
                'verbose_name_plural': "Catégories d'emploi",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre du poste')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug URL')),
                ('description', models.TextField(verbose_name='Description du poste')),
                ('responsibilities', models.TextField(blank=True, verbose_name='Responsabilités')),
                ('requirements', models.TextField(verbose_name='Prérequis')),
                ('benefits', models.TextField(blank=True, verbose_name='Avantages')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salaire minimum')),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salaire maximum')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Devise')),
                ('job_type', models.CharField(choices=[('full_time', 'Temps plein'), ('part_time', 'Temps partiel'), ('cdi', 'CDI'), ('cdd', 'CDD'), ('internship', 'Stage'), ('remote', 'Télétravail'), ('freelance', 'Freelance')], max_length=20, verbose_name='Type de contrat')),
                ('experience_level', models.CharField(choices=[('junior', "Junior (0-2 ans d'expérience)"), ('intermediate', "Intermédiaire (3-5 ans d'expérience"), ('senior', "Senior (5+ ans d'expérience)")], max_length=20, verbose_name="Niveau d'expérience")),
                ('location', models.CharField(max_length=255, verbose_name='Localisation')),
                ('remote_allowed', models.BooleanField(default=False, verbose_name='Télétravail autorisé')),
                ('application_url', models.URLField(blank=True, verbose_name='URL de candidature')),
                ('application_email', models.EmailField(blank=True, max_length=254, verbose_name='Email pour candidature')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('expired', 'Expiré'), ('filled', 'Fermé')], default='draft', max_length=20, verbose_name='Statut')),
                ('featured', models.BooleanField(default=False, verbose_name='Mise en avant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_offers', to='jobs.jobcategory', verbose_name='Catégorie')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to='organizations.organization', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': "Offre d'emploi",
                'verbose_name_plural': "Offres d'emploi",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('applicant_name', models.CharField(max_length=255, verbose_name='Nom du candidat')),
                ('applicant_email', models.EmailField(max_length=254, verbose_name='Email du candidat')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='CV')),
                ('cover_letter', models.TextField(blank=True, verbose_name='Lettre de motivation')),
                ('ai_analysis', models.TextField(blank=True, verbose_name='Analyse IA du CV')),
                ('ai_decision', models.BooleanField(blank=True, null=True, verbose_name='Décision IA')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('job_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.joboffer', verbose_name="Offre d'emploi")),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
