# Generated by Django 5.2.5 on 2025-10-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joboffer',
            name='salary_max',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='salary_min',
        ),
        migrations.AddField(
            model_name='joboffer',
            name='salary',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Salaire'),
        ),
    ]
