# Generated by Django 5.2.5 on 2025-08-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='skills',
            field=models.ManyToManyField(related_name='jobs', to='core.technology', verbose_name='Compétences'),
        ),
    ]
