# Generated by Django 5.1.8 on 2025-08-21 15:48

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobcategory',
            options={'ordering': ['title'], 'verbose_name': "Catégorie d'emploi", 'verbose_name_plural': "Catégories d'emploi"},
        ),
        migrations.RenameField(
            model_name='jobcategory',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', verbose_name='slug'),
        ),
    ]
