# Generated by Django 5.2.5 on 2025-10-17 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_rename_category_to_poste'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('shortlisted', 'Présélectionné'), ('accepted', 'Retenu'), ('rejected', 'Rejeté')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='poste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_offers', to='jobs.jobcategory', verbose_name='Poste'),
        ),
    ]
