# Generated by Django 5.2.5 on 2025-11-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobapplication_assigned_evaluation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='source',
            field=models.CharField(choices=[('spontaneous', 'Candidature Spontanée'), ('matched', 'Candidature Matchée')], default='spontaneous', help_text='Indique si la candidature est spontanée ou issue du système de matching', max_length=20, verbose_name='Source de la candidature'),
        ),
    ]
