# Generated by Django 5.2.5 on 2025-11-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_add_source_to_job_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='documents',
            field=models.JSONField(blank=True, default=dict, help_text='Stocke les URLs des documents additionnels requis (portfolio, diplôme, etc.)', verbose_name='Documents additionnels'),
        ),
    ]
