# Generated by Django 5.2.5 on 2026-02-12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_add_documents_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplicationAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, editable=False, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, editable=False, verbose_name='Date de modification')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('done', 'Terminé'), ('failed', 'Échec')], default='pending', max_length=20, verbose_name='Statut')),
                ('provider', models.CharField(blank=True, choices=[('gemini', 'Gemini'), ('local', 'Local')], max_length=20, null=True, verbose_name='Provider')),
                ('extracted_data', models.JSONField(blank=True, default=dict, verbose_name='Données extraites')),
                ('analysis_markdown', models.TextField(blank=True, verbose_name='Analyse (markdown)')),
                ('decision', models.BooleanField(blank=True, null=True, verbose_name='Décision')),
                ('error', models.TextField(blank=True, verbose_name='Erreur')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Début')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='jobs.jobapplication', verbose_name='Candidature')),
            ],
            options={
                'verbose_name': 'Analyse de candidature',
                'verbose_name_plural': 'Analyses de candidatures',
            },
        ),
    ]
