# Generated by Django 5.2.5 on 2026-02-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_jobapplicationanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_matched',
            field=models.BooleanField(default=False, verbose_name='Matchée'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='match_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Score de matching'),
        ),
    ]
