# Generated by Django 5.2.5 on 2026-02-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_jobapplication_matching_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='source',
            field=models.CharField(choices=[('spontaneous', 'Candidature Spontanée'), ('matched', 'Candidature Matchée'), ('email', 'Candidature par Email')], default='spontaneous', help_text='Indique si la candidature est spontanée ou issue du système de matching', max_length=20, verbose_name='Source de la candidature'),
        ),
    ]
