# Generated by Django 5.2.5 on 2026-02-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_jobapplication_contract_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplicationevaluation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='jobapplicationevaluation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
    ]
