# Generated by Django 5.1.8 on 2025-08-14 16:25

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title',
                                                                   verbose_name='slug')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('level', models.CharField(
                    choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé')],
                    max_length=20, verbose_name='Niveau')),
                ('is_free', models.BooleanField(default=True, verbose_name='Gratuit')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title',
                                                                   verbose_name='slug')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules',
                                             to='learning.course', verbose_name='Cours')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['course', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title',
                                                                   verbose_name='slug')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('content_type', models.CharField(
                    choices=[('video', 'Vidéo'), ('pdf', 'Document PDF'), ('talk', 'Conférence'),
                             ('external', 'Ressource Externe'), ('markdown', 'Markdown')], max_length=15,
                    verbose_name='Content Type')),
                ('resource_file',
                 models.FileField(blank=True, null=True, upload_to='learning/contents/', verbose_name='Fichier')),
                ('resource_url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Contenu')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents',
                                             to='learning.module', verbose_name='Module')),
            ],
            options={
                'verbose_name': 'Contenu',
                'verbose_name_plural': 'Contenus',
                'ordering': ['module', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title',
                                                                   verbose_name='slug')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('module',
                 models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz',
                                      to='learning.module', verbose_name='Module')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quiz',
                'ordering': ['module', 'title'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title',
                                                                   verbose_name='slug')),
                ('title', models.CharField(max_length=255, verbose_name='Question')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('explanation', models.TextField(blank=True, verbose_name='Explication')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions',
                                           to='learning.quiz', verbose_name='Quiz')),
            ],
            options={
                'verbose_name': 'Question de Quiz',
                'verbose_name_plural': 'Questions de Quiz',
                'ordering': ['quiz', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Texte')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Réponse correcte')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices',
                                               to='learning.quizquestion', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Choix de réponse',
                'verbose_name_plural': 'Choix de réponses',
                'ordering': ['question', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Soumis le')),
                ('score', models.FloatField(default=0, verbose_name='Score')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.quiz',
                                           verbose_name='Quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                           verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Résultat de Quiz',
                'verbose_name_plural': 'Résultats de Quiz',
                'ordering': ['-submitted_at'],
                'unique_together': {('user', 'quiz', 'submitted_at')},
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Émis le')),
                ('file', models.FileField(upload_to='certificates/', verbose_name='Fichier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                           verbose_name='Utilisateur')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.course',
                                             verbose_name='Cours')),
            ],
            options={
                'verbose_name': 'Certificat',
                'verbose_name_plural': 'Certificats',
                'ordering': ['-issued_at'],
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Terminé')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé le')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.content',
                                              verbose_name='Contenu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                           verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Progrès',
                'verbose_name_plural': 'Progrès',
                'ordering': ['-completed_at'],
                'unique_together': {('user', 'content')},
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(verbose_name='Correct')),
                ('selected_choices',
                 models.ManyToManyField(to='learning.quizchoice', verbose_name='Choix sélectionnés')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.quizquestion',
                                               verbose_name='Question')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers',
                                             to='learning.quizresult', verbose_name='Résultat')),
            ],
            options={
                'verbose_name': 'Réponse de Quiz',
                'verbose_name_plural': 'Réponses de Quiz',
                'unique_together': {('result', 'question')},
            },
        ),
    ]
