# Generated by Django 5.1.8 on 2025-08-26 17:06

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', verbose_name='slug')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('level', models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé')], max_length=20, verbose_name='Niveau')),
                ('is_free', models.BooleanField(default=True, verbose_name='Gratuit')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('estimated_duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée estimée (heures)')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_created', to=settings.AUTH_USER_MODEL, verbose_name='Instructeur')),
                ('skills', models.ManyToManyField(blank=True, related_name='courses', to='core.technology', verbose_name='Compétence')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Émis le')),
                ('file', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Fichier')),
                ('certificate_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Numéro de certificat')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Valide')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.course', verbose_name='Cours')),
            ],
            options={
                'verbose_name': 'Certificat',
                'verbose_name_plural': 'Certificats',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', verbose_name='slug')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='learning.course', verbose_name='Cours')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['course', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', verbose_name='slug')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('content_type', models.CharField(choices=[('video', 'Vidéo'), ('pdf', 'Document PDF'), ('talk', 'Conférence'), ('external', 'Ressource Externe'), ('markdown', 'Markdown'), ('audio', 'Audio'), ('image', 'Image')], max_length=15, verbose_name='Type de contenu')),
                ('resource_file', models.FileField(blank=True, null=True, upload_to='learning/contents/', verbose_name='Fichier')),
                ('resource_url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Contenu')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée (minutes)')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='learning.module', verbose_name='Module')),
            ],
            options={
                'verbose_name': 'Contenu',
                'verbose_name_plural': 'Contenus',
                'ordering': ['module', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Terminé')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé le')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Commencé le')),
                ('last_accessed', models.DateTimeField(auto_now=True, verbose_name='Dernier accès')),
                ('time_spent_seconds', models.PositiveIntegerField(default=0, verbose_name='Temps passé (secondes)')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.content', verbose_name='Contenu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Progrès',
                'verbose_name_plural': 'Progrès',
                'ordering': ['-last_accessed'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', verbose_name='slug')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('passing_score', models.PositiveIntegerField(default=70, verbose_name='Score de passage (%)')),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Limite de temps (minutes)')),
                ('max_attempts', models.PositiveIntegerField(default=3, verbose_name='Nombre maximum de tentatives')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('randomize_questions', models.BooleanField(default=False, verbose_name='Questions aléatoires')),
                ('module', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='learning.module', verbose_name='Module')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quiz',
                'ordering': ['module', 'title'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', verbose_name='slug')),
                ('title', models.CharField(max_length=500, verbose_name='Question')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('explanation', models.TextField(blank=True, verbose_name='Explication')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('points', models.PositiveIntegerField(default=1, verbose_name='Points')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.quiz', verbose_name='Quiz')),
            ],
            options={
                'verbose_name': 'Question de Quiz',
                'verbose_name_plural': 'Questions de Quiz',
                'ordering': ['quiz', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Texte')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Réponse correcte')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='learning.quizquestion', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Choix de réponse',
                'verbose_name_plural': 'Choix de réponses',
                'ordering': ['question', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Commencé le')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Soumis le')),
                ('score', models.FloatField(default=0, verbose_name='Score')),
                ('total_points', models.PositiveIntegerField(default=0, verbose_name='Points totaux')),
                ('obtained_points', models.PositiveIntegerField(default=0, verbose_name='Points obtenus')),
                ('is_passed', models.BooleanField(default=False, verbose_name='Réussi')),
                ('attempt_number', models.PositiveIntegerField(default=1, verbose_name='Numéro de tentative')),
                ('time_taken_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Temps pris (secondes)')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.quiz', verbose_name='Quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Résultat de Quiz',
                'verbose_name_plural': 'Résultats de Quiz',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Correct')),
                ('points_earned', models.PositiveIntegerField(default=0, verbose_name='Points gagnés')),
                ('selected_choices', models.ManyToManyField(blank=True, to='learning.quizchoice', verbose_name='Choix sélectionnés')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.quizquestion', verbose_name='Question')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='learning.quizresult', verbose_name='Résultat')),
            ],
            options={
                'verbose_name': 'Réponse de Quiz',
                'verbose_name_plural': 'Réponses de Quiz',
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['level', 'is_free', 'is_active'], name='learning_co_level_30b143_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['created_at'], name='learning_co_created_195871_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['certificate_number'], name='learning_ce_certifi_26e67a_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['is_valid'], name='learning_ce_is_vali_cd8e6f_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['issued_at'], name='learning_ce_issued__df073e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together={('user', 'course')},
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['course', 'order'], name='learning_mo_course__7897c1_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['is_active'], name='learning_mo_is_acti_2567ce_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['module', 'order'], name='learning_co_module__0f9ad8_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['content_type'], name='learning_co_content_a79119_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['is_active'], name='learning_co_is_acti_38fe83_idx'),
        ),
        migrations.AddIndex(
            model_name='progress',
            index=models.Index(fields=['user', 'content'], name='learning_pr_user_id_e70732_idx'),
        ),
        migrations.AddIndex(
            model_name='progress',
            index=models.Index(fields=['is_completed'], name='learning_pr_is_comp_99d85a_idx'),
        ),
        migrations.AddIndex(
            model_name='progress',
            index=models.Index(fields=['last_accessed'], name='learning_pr_last_ac_7001d8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together={('user', 'content')},
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['is_active'], name='learning_qu_is_acti_0b4014_idx'),
        ),
        migrations.AddIndex(
            model_name='quizquestion',
            index=models.Index(fields=['quiz', 'order'], name='learning_qu_quiz_id_73fd7c_idx'),
        ),
        migrations.AddIndex(
            model_name='quizquestion',
            index=models.Index(fields=['is_active'], name='learning_qu_is_acti_0a333d_idx'),
        ),
        migrations.AddIndex(
            model_name='quizchoice',
            index=models.Index(fields=['question', 'order'], name='learning_qu_questio_e36e46_idx'),
        ),
        migrations.AddIndex(
            model_name='quizchoice',
            index=models.Index(fields=['is_correct'], name='learning_qu_is_corr_b701d3_idx'),
        ),
        migrations.AddIndex(
            model_name='quizresult',
            index=models.Index(fields=['user', 'quiz'], name='learning_qu_user_id_23421b_idx'),
        ),
        migrations.AddIndex(
            model_name='quizresult',
            index=models.Index(fields=['is_passed'], name='learning_qu_is_pass_32357c_idx'),
        ),
        migrations.AddIndex(
            model_name='quizresult',
            index=models.Index(fields=['started_at'], name='learning_qu_started_df4e3c_idx'),
        ),
        migrations.AddIndex(
            model_name='quizanswer',
            index=models.Index(fields=['result', 'question'], name='learning_qu_result__1747cc_idx'),
        ),
        migrations.AddIndex(
            model_name='quizanswer',
            index=models.Index(fields=['is_correct'], name='learning_qu_is_corr_5b5411_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quizanswer',
            unique_together={('result', 'question')},
        ),
    ]
