# Generated by Django 5.1.8 on 2025-08-14 18:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['module', 'order', 'title'], 'verbose_name': 'Contenu',
                     'verbose_name_plural': 'Contenus'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['course', 'order', 'title'], 'verbose_name': 'Module',
                     'verbose_name_plural': 'Modules'},
        ),
        migrations.AlterModelOptions(
            name='progress',
            options={'ordering': ['-last_accessed'], 'verbose_name': 'Progrès', 'verbose_name_plural': 'Progrès'},
        ),
        migrations.AlterModelOptions(
            name='quizchoice',
            options={'ordering': ['question', 'order', 'id'], 'verbose_name': 'Choix de réponse',
                     'verbose_name_plural': 'Choix de réponses'},
        ),
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'ordering': ['quiz', 'order', 'id'], 'verbose_name': 'Question de Quiz',
                     'verbose_name_plural': 'Questions de Quiz'},
        ),
        migrations.AlterModelOptions(
            name='quizresult',
            options={'ordering': ['-started_at'], 'verbose_name': 'Résultat de Quiz',
                     'verbose_name_plural': 'Résultats de Quiz'},
        ),
        migrations.AlterUniqueTogether(
            name='quizresult',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True,
                                   verbose_name='Numéro de certificat'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='Valide'),
        ),
        migrations.AddField(
            model_name='content',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée (minutes)'),
        ),
        migrations.AddField(
            model_name='content',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AddField(
            model_name='course',
            name='estimated_duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée estimée (heures)'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='courses_created', to=settings.AUTH_USER_MODEL,
                                    verbose_name='Instructeur'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='module',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AddField(
            model_name='progress',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernier accès'),
        ),
        migrations.AddField(
            model_name='progress',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now,
                                       verbose_name='Commencé le'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progress',
            name='time_spent_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='Temps passé (secondes)'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='max_attempts',
            field=models.PositiveIntegerField(default=3, verbose_name='Nombre maximum de tentatives'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='passing_score',
            field=models.PositiveIntegerField(default=70, verbose_name='Score de passage (%)'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='randomize_questions',
            field=models.BooleanField(default=False, verbose_name='Questions aléatoires'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Limite de temps (minutes)'),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='points_earned',
            field=models.PositiveIntegerField(default=0, verbose_name='Points gagnés'),
        ),
        migrations.AddField(
            model_name='quizchoice',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='points',
            field=models.PositiveIntegerField(default=1, verbose_name='Points'),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Numéro de tentative'),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='is_passed',
            field=models.BooleanField(default=False, verbose_name='Réussi'),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='obtained_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Points obtenus'),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now,
                                       verbose_name='Commencé le'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizresult',
            name='time_taken_seconds',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Temps pris (secondes)'),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='total_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Points totaux'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Fichier'),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('video', 'Vidéo'), ('pdf', 'Document PDF'), ('talk', 'Conférence'),
                                            ('external', 'Ressource Externe'), ('markdown', 'Markdown'),
                                            ('audio', 'Audio'), ('image', 'Image')], max_length=15,
                                   verbose_name='Type de contenu'),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Correct'),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='selected_choices',
            field=models.ManyToManyField(blank=True, to='learning.quizchoice', verbose_name='Choix sélectionnés'),
        ),
        migrations.AlterField(
            model_name='quizchoice',
            name='text',
            field=models.CharField(max_length=500, verbose_name='Texte'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Soumis le'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['certificate_number'], name='learning_ce_certifi_26e67a_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['is_valid'], name='learning_ce_is_vali_cd8e6f_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['issued_at'], name='learning_ce_issued__df073e_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['module', 'order'], name='learning_co_module__0f9ad8_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['content_type'], name='learning_co_content_a79119_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['is_active'], name='learning_co_is_acti_38fe83_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['level', 'is_free', 'is_active'], name='learning_co_level_30b143_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['created_at'], name='learning_co_created_195871_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['course', 'order'], name='learning_mo_course__7897c1_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['is_active'], name='learning_mo_is_acti_2567ce_idx'),
        ),
        migrations.AddIndex(
            model_name='progress',
            index=models.Index(fields=['user', 'content'], name='learning_pr_user_id_e70732_idx'),
        ),
        migrations.AddIndex(
            model_name='progress',
            index=models.Index(fields=['is_completed'], name='learning_pr_is_comp_99d85a_idx'),
        ),
        migrations.AddIndex(
            model_name='progress',
            index=models.Index(fields=['last_accessed'], name='learning_pr_last_ac_7001d8_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['is_active'], name='learning_qu_is_acti_0b4014_idx'),
        ),
        migrations.AddIndex(
            model_name='quizanswer',
            index=models.Index(fields=['result', 'question'], name='learning_qu_result__1747cc_idx'),
        ),
        migrations.AddIndex(
            model_name='quizanswer',
            index=models.Index(fields=['is_correct'], name='learning_qu_is_corr_5b5411_idx'),
        ),
        migrations.AddIndex(
            model_name='quizchoice',
            index=models.Index(fields=['question', 'order'], name='learning_qu_questio_e36e46_idx'),
        ),
        migrations.AddIndex(
            model_name='quizchoice',
            index=models.Index(fields=['is_correct'], name='learning_qu_is_corr_b701d3_idx'),
        ),
        migrations.AddIndex(
            model_name='quizquestion',
            index=models.Index(fields=['quiz', 'order'], name='learning_qu_quiz_id_73fd7c_idx'),
        ),
        migrations.AddIndex(
            model_name='quizquestion',
            index=models.Index(fields=['is_active'], name='learning_qu_is_acti_0a333d_idx'),
        ),
        migrations.AddIndex(
            model_name='quizresult',
            index=models.Index(fields=['user', 'quiz'], name='learning_qu_user_id_23421b_idx'),
        ),
        migrations.AddIndex(
            model_name='quizresult',
            index=models.Index(fields=['is_passed'], name='learning_qu_is_pass_32357c_idx'),
        ),
        migrations.AddIndex(
            model_name='quizresult',
            index=models.Index(fields=['started_at'], name='learning_qu_started_df4e3c_idx'),
        ),
    ]
