# Generated by Django 5.2.5 on 2025-11-11 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
        ('organizations', '0002_remove_organization_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de sélection')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.course', verbose_name='Formation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Sélection de formation',
                'verbose_name_plural': 'Sélections de formations',
                'unique_together': {('organization', 'course')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='selected_by_organizations',
            field=models.ManyToManyField(related_name='selected_trainings', through='learning.TrainingSelection', to='organizations.organization', verbose_name='Organisations ayant sélectionné'),
        ),
    ]
