# Generated by Django 5.1.8 on 2025-08-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('learning', '0002_alter_content_options_alter_module_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='instructor',
            new_name='publisher',
        ),
        migrations.AddField(
            model_name='course',
            name='skill',
            field=models.ManyToManyField(blank=True, related_name='courses', to='core.technology', verbose_name='Compétence'),
        ),
    ]
