# Generated by Django 5.2.5 on 2025-11-13 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_courseenrollment'),
        ('learning', '0002_trainingselection_course_selected_by_organizations'),
    ]

    operations = [
    ]
