# Generated by Django 5.1.8 on 2025-08-26 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_rename_instructor_course_publisher_course_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='skill',
            new_name='skills',
        ),
    ]
