# Generated by Django 5.2.5 on 2026-09-09 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_evaluation_candidateprofile_evaluationquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_preview',
            field=models.BooleanField(default=False, verbose_name='Aperçu public'),
        ),
        migrations.AddField(
            model_name='content',
            name='is_required',
            field=models.BooleanField(default=True, verbose_name='Obligatoire'),
        ),
        migrations.AddField(
            model_name='course',
            name='certificate_enabled',
            field=models.BooleanField(default=True, verbose_name='Certificat activé'),
        ),
        migrations.AddField(
            model_name='course',
            name='certificate_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix du certificat'),
        ),
        migrations.AddField(
            model_name='course',
            name='currency',
            field=models.CharField(default='XOF', max_length=3, verbose_name='Devise'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Publié'),
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(default='Français', max_length=100, verbose_name='Langue'),
        ),
        migrations.AddField(
            model_name='course',
            name='learning_objectives',
            field=models.JSONField(blank=True, default=list, verbose_name='Objectifs pédagogiques'),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.JSONField(blank=True, default=list, verbose_name='Prérequis'),
        ),
        migrations.AddField(
            model_name='course',
            name='short_description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Description courte'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Terminée le'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expire le'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='source',
            field=models.CharField(choices=[('self', 'Individuelle'), ('organization', 'Organisation'), ('admin', 'Administration')], default='self', max_length=20, verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Commencée le'),
        ),
        migrations.AddField(
            model_name='progress',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='Durée'),
        ),
        migrations.AddField(
            model_name='progress',
            name='enrollment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_progress', to='learning.courseenrollment'),
        ),
        migrations.AddField(
            model_name='progress',
            name='last_position_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='Dernière position'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Inscrit le'),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Paiement en attente'), ('active', 'Active'), ('completed', 'Terminée'), ('cancelled', 'Annulée'), ('expired', 'Expirée')], default='active', max_length=20, verbose_name='Statut'),
        ),
    ]
