# Generated by Django 5.2.5 on 2026-09-09 14:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_content_is_preview_content_is_required_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-created_at'], 'verbose_name': 'Certificat', 'verbose_name_plural': 'Certificats'},
        ),
        migrations.RemoveIndex(
            model_name='certificate',
            name='learning_ce_issued__df073e_idx',
        ),
        migrations.AddField(
            model_name='certificate',
            name='course_title_snapshot',
            field=models.CharField(blank=True, max_length=255, verbose_name='Titre du cours'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='duration_snapshot',
            field=models.CharField(blank=True, max_length=50, verbose_name='Durée'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='learning.courseenrollment'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='final_score',
            field=models.PositiveIntegerField(default=0, verbose_name='Score final'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='level_snapshot',
            field=models.CharField(blank=True, max_length=20, verbose_name='Niveau'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Métadonnées'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='participant_name_snapshot',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom du participant'),
        ),
    ]
