# Generated by Django 5.2.5 on 2026-09-09 14:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_alter_certificate_options_and_more'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_payment', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='payment_required',
            field=models.BooleanField(default=False, verbose_name='Paiement requis'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Fichier PDF'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='public_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True, verbose_name='UUID public'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Révoqué le'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='revoked_reason',
            field=models.TextField(blank=True, verbose_name='Motif de révocation'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='status',
            field=models.CharField(choices=[('eligible', 'Éligible'), ('payment_pending', 'Paiement en attente'), ('issued', 'Émis'), ('revoked', 'Révoqué')], default='eligible', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modifié le'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='verification_code',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True, verbose_name='Code de vérification'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_payment', to='payments.payment', verbose_name='Paiement'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issued_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Émis le'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['public_uuid'], name='learning_ce_public__aa872b_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['verification_code'], name='learning_ce_verific_fd019d_idx'),
        ),
    ]
