# Generated by Django 5.2.5 on 2026-09-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_certificate_payment_certificate_payment_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('practice', 'Pratique'), ('final', 'Final')], default='practice', max_length=10, verbose_name='Type de quiz'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='max_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre maximum de tentatives'),
        ),
    ]
