# Generated by Django 5.1.8 on 2025-05-05 09:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to=settings.AUTH_USER_MODEL, verbose_name='Compte')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nom complet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Candidat',
                'verbose_name_plural': 'Candidats',
            },
        ),
        migrations.CreateModel(
            name='OrgEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('questions_order', models.IntegerField(choices=[(1, 'Aléatoire'), (2, "Ordre d'ajout"), (3, 'Par compétence')], default=1, verbose_name='Ordre des questions')),
                ('archived', models.BooleanField(default=False, verbose_name='Archivé')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='organizations.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Organisation Evaluation',
                'verbose_name_plural': 'Organisation Evaluations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name="Token d'invitation")),
                ('invited_at', models.DateTimeField(auto_now_add=True, verbose_name='Invité le')),
                ('expires_at', models.DateTimeField(verbose_name='Expire le')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Accepté'), ('declined', 'Refusé'), ('expired', 'Expirée')], default='pending', max_length=20, verbose_name='Statut')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='organizations.candidate', verbose_name='Candidat')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='organizations.orgevaluation', verbose_name='Évaluation')),
            ],
        ),
        migrations.CreateModel(
            name='OrgQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('text', models.TextField(verbose_name='Titre')),
                ('explanation', models.TextField(help_text='Explication de la réponse', verbose_name='Explication')),
                ('difficulty', models.CharField(choices=[('easy', 'Facile'), ('medium', 'Moyen'), ('hard', 'Difficile')], default='medium', max_length=10, verbose_name='Difficulté')),
                ('duration', models.IntegerField(default=100, help_text='Durée en secondes', validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(200)], verbose_name='Durée')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='organizations.orgevaluation', verbose_name='Évaluation')),
                ('original_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_copies', to='questions.question', verbose_name='Question originale')),
                ('technology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_questions', to='core.technology', verbose_name='Technologie')),
            ],
            options={
                'verbose_name': "Question d'organisation",
                'verbose_name_plural': "Questions d'organisation",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrgChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('text', models.TextField(verbose_name='Texte')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Est correct')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='organizations.orgquestion')),
            ],
            options={
                'verbose_name': "Choix d'organisation",
                'verbose_name_plural': "Choix d'organisation",
            },
        ),
        migrations.CreateModel(
            name='OrgSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Résultat')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Soumis le')),
            ],
            options={
                'verbose_name': "Soumission d'organisation",
                'verbose_name_plural': "Soumissions d'organisation",
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['score'], name='organizatio_score_f04412_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrgSubmissionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Commencé le')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé le')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Complété')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='organizations.candidate', verbose_name='Candidat')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='organizations.orgevaluation', verbose_name='Évaluation')),
                ('questions', models.ManyToManyField(blank=True, related_name='attempts', to='organizations.orgquestion', verbose_name='Questions')),
                ('submission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempt', to='organizations.orgsubmission', verbose_name='Soumission')),
            ],
            options={
                'verbose_name': "Tentative de soumission d'organisation",
                'verbose_name_plural': "Tentatives de soumission d'organisation",
            },
        ),
        migrations.CreateModel(
            name='OrgAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='Correcte')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='Répondu le')),
                ('delta_time', models.PositiveSmallIntegerField(verbose_name='Durée')),
                ('status', models.CharField(choices=[('pending', 'En attente de correction'), ('discarded', 'Abandonnée'), ('timeout', 'Timeout'), ('partial', 'Correct partiellement'), ('correct', 'Correcte'), ('incorrect', 'Incorrecte')], default='pending', max_length=20, verbose_name='Statut')),
                ('score', models.IntegerField(default=0, verbose_name='Résultat')),
                ('selected_choices', models.ManyToManyField(blank=True, related_name='answers', to='organizations.orgchoice', verbose_name='Choix sélectionnés')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='organizations.orgquestion', verbose_name='Question')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='organizations.orgsubmissionattempt', verbose_name='Tentative de soumission')),
            ],
            options={
                'verbose_name': "Réponse d'organisation",
                'verbose_name_plural': "Réponses d'organisation",
            },
        ),
        migrations.AddIndex(
            model_name='orgevaluation',
            index=models.Index(fields=['slug'], name='organizatio_slug_3d89f6_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationinvitation',
            index=models.Index(fields=['token'], name='organizatio_token_ce5006_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationinvitation',
            index=models.Index(fields=['status'], name='organizatio_status_8b98c1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluationinvitation',
            unique_together={('evaluation', 'candidate')},
        ),
        migrations.AddIndex(
            model_name='orgquestion',
            index=models.Index(fields=['difficulty'], name='organizatio_difficu_a0807b_idx'),
        ),
        migrations.AddIndex(
            model_name='orgchoice',
            index=models.Index(fields=['question', 'is_correct'], name='organizatio_questio_292f16_idx'),
        ),
        migrations.AddIndex(
            model_name='orgsubmissionattempt',
            index=models.Index(fields=['started_at'], name='organizatio_started_94409f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='orgsubmissionattempt',
            unique_together={('evaluation', 'candidate')},
        ),
        migrations.AddIndex(
            model_name='organswer',
            index=models.Index(fields=['status'], name='organizatio_status_9137f6_idx'),
        ),
        migrations.AddIndex(
            model_name='organswer',
            index=models.Index(fields=['is_correct'], name='organizatio_is_corr_04c42c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organswer',
            unique_together={('attempt', 'question')},
        ),
    ]
