# Generated by Django 5.1.8 on 2025-06-19 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluationinvitation',
            options={'ordering': ['-invited_at']},
        ),
        migrations.AlterField(
            model_name='evaluationinvitation',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to='organizations.candidate', verbose_name='Candidat'),
        ),
    ]
