# Generated by Django 5.1.8 on 2025-07-07 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_add_default_domain_profession'),
        ('organizations', '0003_organization_address_organization_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgevaluation',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='core.profession', verbose_name='Profession'),
        ),
        migrations.AddField(
            model_name='orgevaluation',
            name='type',
            field=models.CharField(
                choices=[('technical', 'Technique'), ('logical', 'Logique'), ('personality', 'Personnalité')],
                default='technical', max_length=20, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='orgsubmission',
            name='personality_detail',
            field=models.TextField(blank=True, null=True, verbose_name='Personnalité'),
        ),
        migrations.AddField(
            model_name='orgsubmissionattempt',
            name='corrected',
            field=models.BooleanField(default=False, verbose_name='Corrigée'),
        ),
    ]
