# Generated by Django 5.1.8 on 2025-05-05 09:24

import candidates.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Localisation')),
                ('short_bio', models.TextField(blank=True, max_length=255, verbose_name='Courte biographie')),
                ('biography', models.TextField(blank=True, verbose_name='Biographie')),
                ('disability', models.BooleanField(default=False, verbose_name='Handicap')),
                ('years_experience', models.PositiveSmallIntegerField(null=True, verbose_name='Expérience professionnelle')),
                ('other_years_experience', models.PositiveSmallIntegerField(null=True, verbose_name='Autre expérience')),
                ('highest_degree', models.PositiveSmallIntegerField(help_text='Bac + X', null=True, verbose_name='Diplôme le plus élevé')),
                ('interested_by', models.CharField(blank=True, max_length=512, verbose_name='Intéressé par')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.profession', verbose_name='Profession')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
                'ordering': ('user__first_name', '-created_at', 'profession__title'),
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('year_of_graduation', models.PositiveSmallIntegerField(verbose_name='Année de diplomation')),
                ('speciality', models.CharField(blank=True, max_length=255, null=True, verbose_name='Spécialité')),
                ('diploma', models.CharField(max_length=255, verbose_name='Diplôme')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='candidates.candidateprofile', verbose_name='Profil')),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ('-year_of_graduation', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('company', models.CharField(max_length=255, verbose_name='Entreprise')),
                ('location', models.CharField(max_length=255, verbose_name='Localisation')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('description', models.TextField(verbose_name='Description')),
                ('still_working', models.BooleanField(default=False, verbose_name='Toujours en poste')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='candidates.candidateprofile', verbose_name='Profil')),
            ],
            options={
                'verbose_name': 'Expérience professionnelle',
                'verbose_name_plural': 'Expériences professionnelles',
                'ordering': ('-start_date', '-end_date', 'title', 'company'),
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nom')),
                ('level', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Niveau')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='candidates.candidateprofile', verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Langue',
                'verbose_name_plural': 'Langues',
                'ordering': ('name', 'level'),
            },
        ),
        migrations.CreateModel(
            name='ProfileTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Niveau')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_technologies', to='candidates.candidateprofile', verbose_name='Profil')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_technologies', to='core.technology', verbose_name='Technologie')),
            ],
            options={
                'verbose_name': 'Technologie de profil',
                'verbose_name_plural': 'Technologies de profil',
                'ordering': ('id',),
                'unique_together': {('profile', 'technology')},
            },
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='technologies',
            field=models.ManyToManyField(related_name='profiles', through='candidates.ProfileTechnology', to='core.technology', verbose_name='Technologies'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Lien')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='candidates.candidateprofile', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('image', models.ImageField(upload_to=candidates.models.upload_image_to, verbose_name='Image')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='candidates.project', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Image de projet',
                'verbose_name_plural': 'Images de projet',
            },
        ),
    ]
