# Generated by Django 5.2.5 on 2026-09-09 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0006_alter_certificate_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('course_enrollment', 'Inscription à une formation'), ('certificate', 'Attestation/certificat')], max_length=30, verbose_name='Objet')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('currency', models.CharField(default='XOF', max_length=3, verbose_name='Devise')),
                ('provider', models.CharField(choices=[('cinetpay', 'CinetPay'), ('stripe', 'Stripe'), ('paypal', 'PayPal')], max_length=20, verbose_name='Prestataire')),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Référence prestataire')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('succeeded', 'Réussi'), ('failed', 'Échoué'), ('cancelled', 'Annulé'), ('refunded', 'Remboursé')], default='pending', max_length=20, verbose_name='Statut')),
                ('failure_reason', models.CharField(blank=True, max_length=255, verbose_name="Raison d'échec")),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Payé le')),
                ('checkout_url', models.URLField(blank=True, verbose_name='URL de paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('webhook_payload', models.JSONField(blank=True, default=dict, verbose_name='Payload webhook')),
                ('webhook_signature', models.CharField(blank=True, max_length=500, verbose_name='Signature webhook')),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='learning.certificate')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='learning.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='payments_pa_user_id_01767a_idx'), models.Index(fields=['provider', 'provider_reference'], name='payments_pa_provide_44281d_idx'), models.Index(fields=['course', 'purpose'], name='payments_pa_course__6d5731_idx')],
            },
        ),
    ]
