# Generated by Django 5.2.5 on 2026-09-17 10:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0003_add_more_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom de l’établissement')),
                ('code', models.SlugField(max_length=80, unique=True, verbose_name='Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
            ],
            options={
                'verbose_name': 'Établissement',
                'verbose_name_plural': 'Établissements',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MANAGER', 'Responsable d’établissement'), ('TEACHER', 'Enseignant')], max_length=20, verbose_name='Rôle')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='education.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personnel scolaire',
                'verbose_name_plural': 'Personnel scolaire',
            },
        ),
        migrations.CreateModel(
            name='AcademicClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nom de la classe')),
                ('level', models.CharField(max_length=120, verbose_name='Niveau')),
                ('academic_year', models.CharField(max_length=20, verbose_name='Année scolaire')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='education.school')),
                ('teachers', models.ManyToManyField(blank=True, related_name='classes_taught', to='education.schoolstaff')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ['school', 'level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(blank=True, max_length=80, verbose_name='Matricule')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='education.academicclass')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='education.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Élève / étudiant',
                'verbose_name_plural': 'Élèves / étudiants',
                'ordering': ['academic_class', 'user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Matière')),
                ('code', models.CharField(blank=True, max_length=40, verbose_name='Code')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='education.school')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('instructions', models.TextField(blank=True, verbose_name='Consignes')),
                ('starts_at', models.DateTimeField(verbose_name='Début')),
                ('ends_at', models.DateTimeField(verbose_name='Fin')),
                ('duration_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Durée (minutes)')),
                ('max_attempts', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Tentatives autorisées')),
                ('grading_scale', models.PositiveSmallIntegerField(choices=[(20, 'Sur 20'), (100, 'Sur 100')], default=20, verbose_name='Barème')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='education.academicclass')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_exams_created', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='education.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='education.subject')),
            ],
            options={
                'verbose_name': 'Épreuve scolaire',
                'verbose_name_plural': 'Épreuves scolaires',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Points')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Position')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='education.exam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_exam_questions', to='questions.question')),
            ],
            options={
                'ordering': ['position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('exam', 'question'), name='unique_exam_question')],
            },
        ),
        migrations.AddConstraint(
            model_name='schoolstaff',
            constraint=models.UniqueConstraint(fields=('user', 'school'), name='unique_school_staff'),
        ),
        migrations.AddConstraint(
            model_name='academicclass',
            constraint=models.UniqueConstraint(fields=('school', 'name', 'academic_year'), name='unique_school_class_year'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_school_subject'),
        ),
    ]
