# Generated by Django 5.2.5 on 2026-09-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_exam_results_published_examattempt_examanswer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='fraud_flag',
            field=models.BooleanField(default=False, verbose_name='Signalement à vérifier'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='fraud_reason',
            field=models.TextField(blank=True, verbose_name='Motif du signalement'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='integrity_events',
            field=models.JSONField(blank=True, default=list, verbose_name='Événements d’intégrité'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='started_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de début'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='submitted_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de remise'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='Navigateur'),
        ),
    ]
