# Generated by Django 5.2.5 on 2026-09-21 09:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_examattempt_fraud_flag_examattempt_fraud_reason_and_more'),
        ('questions', '0003_add_more_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Texte')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Correcte')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Position')),
            ],
            options={
                'verbose_name': 'Choix enseignant',
                'verbose_name_plural': 'Choix enseignants',
                'ordering': ['position'],
            },
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='school_exam_questions', to='questions.question'),
        ),
        migrations.AddField(
            model_name='examanswer',
            name='selected_teacher_choices',
            field=models.ManyToManyField(blank=True, related_name='exam_answers', to='education.teacherchoice'),
        ),
        migrations.CreateModel(
            name='TeacherQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('question_type', models.CharField(choices=[('MCQ', 'Choix multiple'), ('UCQ', 'Choix unique'), ('OA', 'Réponse ouverte')], default='UCQ', max_length=3, verbose_name='Type de question')),
                ('points', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Points par défaut')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifiée le')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_questions', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_questions', to='education.subject')),
            ],
            options={
                'verbose_name': 'Question enseignant',
                'verbose_name_plural': 'Questions enseignants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='teacherchoice',
            name='teacher_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='education.teacherquestion'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='teacher_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exam_questions', to='education.teacherquestion'),
        ),
        migrations.AddConstraint(
            model_name='examquestion',
            constraint=models.UniqueConstraint(fields=('exam', 'teacher_question'), name='unique_exam_teacher_question'),
        ),
    ]
