# Generated by Django 5.1.8 on 2025-08-08 16:36

import apps.evaluations.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nom complet')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates',
                                            to=settings.AUTH_USER_MODEL, verbose_name='Créateur')),
            ],
            options={
                'verbose_name': 'Candidat',
                'verbose_name_plural': 'Candidats',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.evaluations.models._upload_to,
                                            verbose_name='Image')),
                ('difficulty', models.CharField(choices=[('beginner', "Débutant 0- 2 ans d'expérience"),
                                                         ('intermediate', "Intermédiaire 3-5 ans d'expérience"),
                                                         ('expert', "Expert 5+ ans d'expérience")], db_index=True,
                                                default='beginner', max_length=20, verbose_name='Difficulty')),
                ('evaluation_type', models.CharField(
                    choices=[('competition', 'Competition'), ('technical', 'Technique'), ('logical', 'Logique'),
                             ('personality', 'Personnalité')], db_index=True, default='technical', max_length=20,
                    verbose_name='Type')),
                ('questions_order',
                 models.IntegerField(choices=[(1, 'Aléatoire'), (2, "Ordre d'ajout"), (3, 'Par compétence')], default=2,
                                     verbose_name='Ordre des questions')),
                ('archived', models.BooleanField(db_index=True, default=False, verbose_name='Archivé')),
                ('profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='evaluations', to='core.profession',
                                                 verbose_name='Profession')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations',
                                                to=settings.AUTH_USER_MODEL, verbose_name='Créateur')),
                ('questions', models.ManyToManyField(blank=True, related_name='evaluations', to='questions.question',
                                                     verbose_name='Questions')),
                ('technology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='evaluations', to='core.technology',
                                                 verbose_name='Technologie')),
            ],
            options={
                'verbose_name': 'Evaluation',
                'verbose_name_plural': 'Evaluations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Commencé le')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('evaluation', models.OneToOneField(limit_choices_to={'evaluation_type': 'competition'},
                                                    on_delete=django.db.models.deletion.CASCADE,
                                                    related_name='competition', to='evaluations.evaluation',
                                                    verbose_name='Évaluation')),
            ],
            options={
                'verbose_name': 'Competition',
                'verbose_name_plural': 'Competitions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Résultat')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Soumis le')),
                ('personality_detail', models.TextField(blank=True, null=True, verbose_name='Personnalité')),
            ],
            options={
                'verbose_name': 'Soumission',
                'verbose_name_plural': 'Soumissions',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['score'], name='evaluations_score_b19aab_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubmissionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_object_id', models.PositiveIntegerField()),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Commencé le')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé le')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Complété')),
                ('corrected', models.BooleanField(default=False, verbose_name='Corrigée')),
                ('candidate_content_type',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts',
                                                 to='evaluations.evaluation', verbose_name='Évaluation')),
                ('questions', models.ManyToManyField(blank=True, related_name='attempts', to='questions.question',
                                                     verbose_name='Questions')),
                ('submission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                    related_name='attempt', to='evaluations.submission',
                                                    verbose_name='Soumission')),
            ],
            options={
                'verbose_name': 'Tentative de soumission',
                'verbose_name_plural': 'Tentatives de soumission',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(blank=True, db_index=True, null=True, verbose_name='Correcte')),
                ('answered_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Répondu le')),
                ('delta_time',
                 models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(200)],
                                                  verbose_name='Durée')),
                ('status', models.CharField(
                    choices=[('pending', 'En attente de correction'), ('discarded', 'Abandonnée'),
                             ('timeout', 'Timeout'), ('partial', 'Correct partiellement'), ('correct', 'Correcte'),
                             ('incorrect', 'Incorrecte')], db_index=True, default='pending', max_length=20,
                    verbose_name='Statut')),
                ('score', models.IntegerField(default=0, verbose_name='Résultat')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers',
                                               to='questions.question', verbose_name='Question')),
                ('selected_choices', models.ManyToManyField(blank=True, related_name='answers', to='questions.choice',
                                                            verbose_name='Choix sélectionnés')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers',
                                              to='evaluations.submissionattempt',
                                              verbose_name='Tentative de soumission')),
            ],
            options={
                'verbose_name': 'Réponse',
                'verbose_name_plural': 'Réponses',
            },
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['slug'], name='evaluations_slug_f3a994_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['difficulty'], name='evaluations_difficu_05aff5_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['archived'], name='evaluations_archive_792c49_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionattempt',
            index=models.Index(fields=['started_at'], name='evaluations_started_7b3ff1_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['status'], name='evaluations_status_620da5_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['is_correct'], name='evaluations_is_corr_60035d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('attempt', 'question')},
        ),
    ]
