# Generated by Django 5.2.5 on 2025-08-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),
        ('questions', '0002_question_weight'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='submissionattempt',
            index=models.Index(fields=['participant', 'evaluation'], name='evaluations_partici_811904_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionattempt',
            index=models.Index(fields=['is_completed'], name='evaluations_is_comp_457fe3_idx'),
        ),
    ]
