# Generated by Django 5.1.8 on 2025-08-12 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('evaluations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionattempt',
            name='candidate_content_type',
        ),
        migrations.RemoveField(
            model_name='submissionattempt',
            name='candidate_object_id',
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('user', 'Utilisateur'), ('candidate', 'Candidat')], db_index=True,
                                          max_length=20, verbose_name='Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                to='evaluations.candidate', verbose_name='Candidat')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                           to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
            },
        ),
        migrations.AddField(
            model_name='submissionattempt',
            name='participant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attempts',
                                    to='evaluations.participant', verbose_name='Participant'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EvaluationInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name="Token d'invitation")),
                ('invited_at', models.DateTimeField(auto_now_add=True, verbose_name='Invité le')),
                ('expires_at', models.DateTimeField(verbose_name='Expire le')),
                ('status', models.CharField(
                    choices=[('pending', 'En attente'), ('accepted', 'Accepté'), ('declined', 'Refusé'),
                             ('expired', 'Expirée')], default='pending', max_length=20, verbose_name='Statut')),
                ('candidate',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invitation',
                                      to='evaluations.candidate', verbose_name='Candidat')),
                ('evaluation',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations',
                                   to='evaluations.evaluation', verbose_name='Évaluation')),
            ],
            options={
                'ordering': ['-invited_at'],
                'indexes': [models.Index(fields=['token'], name='evaluations_token_2ac89f_idx'),
                            models.Index(fields=['status'], name='evaluations_status_c1d100_idx')],
                'unique_together': {('evaluation', 'candidate')},
            },
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.CheckConstraint(
                condition=models.Q(models.Q(('candidate__isnull', True), ('user__isnull', False)),
                                   models.Q(('candidate__isnull', False), ('user__isnull', True)), _connector='OR'),
                name='participant_exclusive_user_or_candidate'),
        ),
    ]
