# Generated by Cascade to ensure missing column 'questions_order' exists on evaluations_evaluation
from django.db import migrations


def ensure_questions_order(apps, schema_editor):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        cursor.execute("SELECT column_name FROM information_schema.columns WHERE table_name = 'evaluations_evaluation' AND column_name = 'questions_order'")
        cols = [row[0] for row in cursor.fetchall()]
        if 'questions_order' not in cols:
            # Default value 2 corresponds to QuestionOrder.ADDED in models
            schema_editor.execute(
                "ALTER TABLE evaluations_evaluation ADD COLUMN questions_order INTEGER NOT NULL DEFAULT 2"
            )


def noop(apps, schema_editor):
    # No reverse operation
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0002_submissionattempt_evaluations_partici_811904_idx_and_more"),
    ]

    operations = [
        migrations.RunPython(ensure_questions_order, reverse_code=noop),
    ]
