# Generated by Django 5.1.8 on 2025-07-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='explanation',
            field=models.TextField(blank=True, verbose_name='Explication'),
        ),
    ]
