# Generated by Django 5.1.8 on 2025-07-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_quizquestion_explanation'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='content',
            name='content_type_fields_match',
        ),
        migrations.RemoveField(
            model_name='content',
            name='type',
        ),
        migrations.AddField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('video', 'Vidéo'), ('pdf', 'Document PDF'), ('talk', 'Conférence'), ('external', 'Ressource Externe'), ('markdown', 'Markdown')], default='markdown', max_length=15, verbose_name='Content Type'),
            preserve_default=False,
        ),
    ]
