# Generated by Django 5.1.8 on 2025-07-15 14:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('learning', '0003_remove_content_content_type_fields_match_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now,
                                       verbose_name='Date de création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='content',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents',
                                    to='learning.module', verbose_name='Module'),
        ),
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules',
                                    to='learning.course', verbose_name='Cours'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='module',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz',
                                       to='learning.module', verbose_name='Module'),
        ),
    ]
