# Generated by Django 5.2.5 on 2026-07-21 10:55

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('count', models.IntegerField(default=0, verbose_name='Nombre de requêtes')),
            ],
            options={
                'verbose_name': 'Utilisation GEMINI API',
                'verbose_name_plural': 'Utilisation GEMINI API',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_challenge_duration', models.DurationField(default=datetime.timedelta(seconds=3600), verbose_name="Durée par défaut d'un challenge")),
                ('beginner_challenge_duration', models.DurationField(default=datetime.timedelta(seconds=3600), verbose_name="Durée d'un challenge pour les débutants")),
                ('intermediate_challenge_duration', models.DurationField(default=datetime.timedelta(seconds=3600), verbose_name="Durée d'un challenge pour les intermédiaires")),
                ('advanced_challenge_duration', models.DurationField(default=datetime.timedelta(seconds=3600), verbose_name="Durée d'un challenge pour les avancés")),
                ('is_database_already_populated', models.BooleanField(default=False, verbose_name='Base de données déjà peuplée')),
                ('open_answer_question_count_per_tag', models.PositiveIntegerField(default=5, verbose_name='Nombre de réponses ouvertes par tag')),
                ('multiple_choice_question_count_per_tag', models.PositiveIntegerField(default=3, verbose_name='Nombre de questions multiples choix par tag')),
                ('unique_choice_question_count_per_tag', models.PositiveIntegerField(default=2, verbose_name='Nombre de questions choix unique par tag')),
            ],
            options={
                'verbose_name': 'Paramètre',
                'verbose_name_plural': 'Paramètres',
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('duration', models.DurationField(blank=True, help_text='Durée en HH:MM:SS', verbose_name='Durée')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug')),
                ('is_logical', models.BooleanField(default=False, verbose_name='Test logique')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='questions.domain', verbose_name='Domaine')),
                ('questions', models.ManyToManyField(blank=True, related_name='challenges', to='questions.question', verbose_name='Questions')),
            ],
            options={
                'verbose_name': 'Challenge',
                'verbose_name_plural': 'Challenges',
            },
        ),
        migrations.CreateModel(
            name='PersonalityChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug')),
                ('personality_detail', models.TextField(blank=True, null=True, verbose_name='Détails de la personne')),
                ('is_passed', models.BooleanField(default=False, verbose_name='Passé')),
                ('corrected', models.BooleanField(default=False, verbose_name='Corrigé')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personality_challenges', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('questions', models.ManyToManyField(blank=True, related_name='personality_challenges', to='questions.question', verbose_name='Questions')),
            ],
            options={
                'verbose_name': 'Challenge de Personnalité',
                'verbose_name_plural': 'Challenges de Personnalité',
            },
        ),
        migrations.CreateModel(
            name='PersonalityAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Réponse textuelle')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='Répondu le')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personality_answers', to='questions.question', verbose_name='Question')),
                ('selected_choices', models.ManyToManyField(blank=True, related_name='personality_submissions', to='questions.choice', verbose_name='Choix sélectionnés')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='challenges.personalitychallenge', verbose_name='Soumission')),
            ],
            options={
                'verbose_name': 'Réponse de Personnalité',
                'verbose_name_plural': 'Réponses de personnalités',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.FloatField(blank=True, null=True, verbose_name='Résultat')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('CORRECTED', 'Corrigé')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Soumis le')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='challenges.challenge', verbose_name='Challenge')),
            ],
            options={
                'verbose_name': 'Soumission',
                'verbose_name_plural': 'Soumissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Réponse textuelle')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='Correcte')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='Répondu le')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.question', verbose_name='Question')),
                ('selected_choices', models.ManyToManyField(blank=True, related_name='submissions', to='questions.choice', verbose_name='Choix sélectionnés')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='challenges.submission', verbose_name='Soumission')),
            ],
            options={
                'verbose_name': 'Réponse',
                'verbose_name_plural': 'Réponses',
            },
        ),
        migrations.CreateModel(
            name='SubmissionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Commencé le')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé le')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='challenges.challenge', verbose_name='Challenge')),
                ('submission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempt', to='challenges.submission', verbose_name='Soumission')),
            ],
            options={
                'verbose_name': 'Tentative de soumission',
                'verbose_name_plural': 'Tentatives de soumission',
            },
        ),
    ]
