# Generated by Django 5.2.5 on 2026-07-22 11:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalitychallenge',
            name='duration',
            field=models.DurationField(blank=True, help_text='Durée en HH:MM:SS', null=True, verbose_name='Durée'),
        ),
        migrations.CreateModel(
            name='TestDurationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_level', models.IntegerField(choices=[(1, 'Débutant'), (2, 'Intermédiaire'), (3, 'Expert')], default=1, verbose_name="Niveau d'expérience")),
                ('technical_duration', models.DurationField(default=datetime.timedelta(seconds=1800), verbose_name='Durée test technique')),
                ('logical_duration', models.DurationField(default=datetime.timedelta(seconds=2400), verbose_name='Durée test psychotechnique')),
                ('personality_duration', models.DurationField(default=datetime.timedelta(seconds=3600), verbose_name='Durée test de personnalité')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='durations', to='questions.domain', verbose_name='Domaine')),
            ],
            options={
                'verbose_name': 'Profil de durée',
                'verbose_name_plural': 'Profils de durée',
                'unique_together': {('domain', 'experience_level')},
            },
        ),
    ]
