# Generated by Django 5.2.5 on 2026-08-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_personalitychallenge_duration_testdurationprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalitychallenge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créé le'),
        ),
    ]
