# Generated by Django 5.2.5 on 2026-09-17 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_personalitychallenge_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom de la campagne')),
                ('position', models.CharField(max_length=255, verbose_name='Poste')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Début')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('OPEN', 'Ouverte'), ('CLOSED', 'Clôturée'), ('ARCHIVED', 'Archivée')], default='DRAFT', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recruitment_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campagne de recrutement',
                'verbose_name_plural': 'Campagnes de recrutement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='personalitychallenge',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personality_challenges', to='challenges.recruitmentcampaign'),
        ),
        migrations.AddField(
            model_name='submission',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='challenges.recruitmentcampaign'),
        ),
        migrations.AddField(
            model_name='submissionattempt',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_attempts', to='challenges.recruitmentcampaign'),
        ),
        migrations.CreateModel(
            name='CampaignCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('INVITED', 'Invité'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminé'), ('REJECTED', 'Écarté'), ('HIRED', 'Retenu')], default='INVITED', max_length=20, verbose_name='Statut')),
                ('invited_at', models.DateTimeField(auto_now_add=True, verbose_name='Invité le')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_memberships', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='challenges.recruitmentcampaign')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('campaign', 'candidate'), name='unique_campaign_candidate')],
            },
        ),
    ]
