# Generated by Django 5.2.5 on 2025-10-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='address',
        ),
        migrations.AddField(
            model_name='organization',
            name='company_size',
            field=models.CharField(blank=True, choices=[('micro', 'Micro-entreprise (1 à 9 employés)'), ('small', 'Petite entreprise (10 à 49 employés)'), ('medium', 'Entreprise moyenne (50 à 249 employés)'), ('large', 'Grande entreprise (250 à 999 employés)'), ('enterprise', 'Très grande entreprise (1000+ employés)')], max_length=20, null=True, verbose_name="Taille de l'entreprise"),
        ),
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email de l'entreprise"),
        ),
        migrations.AddField(
            model_name='organization',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=255, verbose_name='Quartier'),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name="Téléphone de l'entreprise"),
        ),
        migrations.AddField(
            model_name='organization',
            name='sector',
            field=models.CharField(blank=True, max_length=255, verbose_name="Secteur d'activité"),
        ),
    ]
