# Generated by Django 5.2.5 on 2025-11-11 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_add_notification_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
