# Generated by Django 5.2.5 on 2025-11-12 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0004_populate_evaluation_technologies'),
        ('jobs', '0007_add_documents_field'),
        ('learning', '0001_initial'),
        ('organizations', '0003_add_notification_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('evaluation_assigned', 'Évaluation assignée'), ('interview_scheduled', 'Entretien programmé'), ('application_accepted', 'Candidature acceptée - Recruté'), ('training_assigned', 'Formation assignée'), ('application_rejected', 'Candidature rejetée'), ('application_shortlisted', 'Candidature présélectionnée')], max_length=50, verbose_name='Type de notification')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('related_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to='jobs.jobapplication', verbose_name='Candidature associée')),
                ('related_evaluation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to='evaluations.evaluation', verbose_name='Évaluation associée')),
                ('related_training', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to='learning.course', verbose_name='Formation associée')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Notification Utilisateur',
                'verbose_name_plural': 'Notifications Utilisateur',
                'ordering': ['-created_at'],
            },
        ),
    ]
