# Generated by Django 5.2.5 on 2025-11-13 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_delete_notification'),
        ('organizations', '0004_usernotification'),
    ]

    operations = [
    ]
