# Generated by Django 5.2.5 on 2026-09-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('interview_reminder', "Rappel d'entretien"), ('test_completed', 'Test terminé'), ('new_application', 'Nouvelle candidature'), ('contract_sent', 'Contrat envoyé'), ('contract_signed', 'Contrat signé')], max_length=50, verbose_name='Type de notification'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='type',
            field=models.CharField(choices=[('evaluation_assigned', 'Évaluation assignée'), ('interview_scheduled', 'Entretien programmé'), ('application_accepted', 'Candidature acceptée - Recruté'), ('training_assigned', 'Formation assignée'), ('application_rejected', 'Candidature rejetée'), ('application_shortlisted', 'Candidature présélectionnée'), ('contract_sent', 'Contrat envoyé'), ('contract_signed', 'Contrat signé')], max_length=50, verbose_name='Type de notification'),
        ),
    ]
